JC = javac
CLASSES = Deadwood Action Actor Board CastingOffice Currency decklist Game Player PseudoPlayer Role Room Scene SceneRoom UI gameboard


run:
	java $(CLASSES)

build:
	$(JC) *.java
clean:
	rm *.class
